import scrapy

class PreviredItem(scrapy.Item):
    mes = scrapy.Field()
    periodo_remuneracion = scrapy.Field()
    uf_valor = scrapy.Field()
    uf_fecha = scrapy.Field()
    renta_tope_afp = scrapy.Field()
    renta_tope_ips = scrapy.Field()
    renta_tope_cesantia = scrapy.Field()
    afp_tasas = scrapy.Field()
    afc_tasas = scrapy.Field()
    apv_tope_mensual = scrapy.Field()
    apv_tope_anual = scrapy.Field()
    deposito_convenido_tope = scrapy.Field()
    utm_valor = scrapy.Field()
    uta_valor = scrapy.Field()
    renta_minima_dependientes = scrapy.Field()
    renta_minima_menores = scrapy.Field()
    renta_minima_casa_particular = scrapy.Field()
    renta_minima_no_remuneracional = scrapy.Field()
    seguro_social_tasa = scrapy.Field()
    sis_tasa = scrapy.Field()
    salud_ccaf = scrapy.Field()
    salud_fonasa = scrapy.Field()
    trabajo_pesado_tasa = scrapy.Field()
    trabajo_menos_pesado_tasa = scrapy.Field()
    asignacion_familiar = scrapy.Field()

class UtmItem(scrapy.Item):
    mes = scrapy.Field()
    utm = scrapy.Field()
    uta = scrapy.Field()
    ipc_puntos = scrapy.Field()
    variacion_mensual = scrapy.Field()
    variacion_acumulada = scrapy.Field()
    variacion_anual = scrapy.Field()
